apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: flask
    stage: dev
  ports:
    - name: flask
      protocol: TCP
      port: 80
      targetPort: flask
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask
  namespace: dev
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask
        stage: dev
    spec:
      restartPolicy: Always
      containers:
      - name: web
        image: 270870090353.dkr.ecr.us-east-1.amazonaws.com/dev-flask:latest
        env:
        - name: STAGE
          value: "dev"
        ports:
        - name: flask
          containerPort: 8000
