kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: normal
  namespace: dev-postgres
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: us-east-1b, us-east-1c
reclaimPolicy: Delete
